# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "Isac Cantu Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Isac Cantu"
        tagline = "General Manager"
       # avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: isac_can2@yahoo.com"
        title = "isac_can2@yahoo.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+2066970533"
        title = "+12066970533"

        [[params.contact.list]]
        class = ""
        icon = ""
        url = ""
        title = ""

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/isac-cantu-52625614"
        title = "linkedin.com/in/isac-cantu-52625614"

        [[params.contact.list]]
        class = ""
        icon = ""
        url = ""
        title = ""

        [[params.contact.list]]
        class = ""
        icon = ""
        url = ""
        title = ""

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "General Studies"
        college = "Seattle Central Community College"
        dates = ""

        [[params.education.list]]
        degree = "Food Science"
        college = "South Seattle Community College"
        dates = ""

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Spanish"
        level = "Professional"

 

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "General Manager"
        summary = "Over **twenty years** of success in utilizing personal service skills, providing exceptional service while **achieving managment objectives**. \n\n Versatile and **hard-working professional** with proven history of progressive managment experience in the restaurant industry. \n\n **Excellent communicator** with strong interpersonal abilities to build strategic customer, staff and vendor relationships to promote positive internal and external customer relations. \n\n **Self-motivated professional** with demonstrated abilities and knowledge about products being sold and ability to ensure cost controls without compromising customer service. \n\n **Strong problem resolution skills** to resolve issues and recognized leadership abilities to mentor and coach staff as a team leader and motivator who works well under pressure."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "General Manager"
        dates = "October 2014 - May 2018"
        company = "Collections Cafe at Chihuly Garden & Glass - Seattle, WA"
        details = "Performed operational duties of the food and beverage department. Managed administrative duties by accurately entering invoices, reviewing financial statements and following budgets. \n\n Trained, coached and mentored staff to ensure smooth adoption of new programs as well as old. \n\n Maintained beverage cost under budget by .7% through 2017, maintenance of the dining room and bar supplies under the 2017 budget while the cafe grossed over $400K for the year. \n\n Organized and planned for private events and banquets for groups of 25-1,000. \n\n Coordinated with supervisors and assistant manager to maintain optimal standards in a high-output setting while taking into consideration scheduling, meeting labor targets, service standards, food quality, cleanliness, and safety codes. "

        [[params.jobs.list]]
        position = "Assistant Manager"
        dates = "February 2013 - October 2013"
        company = "Wildfin American Grill - Renton, WA"
        details = "Assisted with opening the second Widlfin location in the Renton Landing in February 2013.  \n\n  Recruitment, interviewing, hiring and training of 55 front of house service staff members. \n\n Fiscally responsible for inventory, labor and purchasing; management of invoicing and purchase entries into RSI external accounting system and preperation of cash reconciliation and bank deposits. \n\n Weekly staff assesments, service sequences, measurement reviews and product quality reviews.  \n\n Oversight of daily operations, management of service staff plus scheduling, labor forecasting and budgeting."

        [[params.jobs.list]]
        position = "General Manager"
        dates = "July 2001 to September 2012"
        company = "Sunset Alehouse and Jacks Grill Inc - Issaquah, WA"
        details = "Assisted with the opening of Sunset Ale House in October 2010, training nad hiring of FOH and BOH staff, inventory, preparing and conducting food menus and beverage classes, managing P&L, payroll and deposits. \n\n  Worked closely with the owners to focus on best practices to achieve an optimal work environment and foster growth for staff.  \n\n  Development and maintenance of a rotating craft beer and beverage menus. \n\n Maintained and updated point of sale system by conducting thorough weekly checks."

       [[params.jobs.list]]
        position = "Manager"
        dates = "October 2007 to June 2008"
        company = "Red House Beer and Wine Shoppe - Renton, WA"
        details = "Responsible for daily retail and restaurant operations including beer and wine purchases, inventory, and merchandising of products, daily cash reconciliation and preparation of bank deposits. \n\n Developed and trained staff with wine and beer knowledge and education. \n\n Managment of event planning for group functions of 20-50 guests."
     
     [[params.jobs.list]]
        position = "Manager"
        dates = "September 2002 to January 2007"
        company = "Aqua by El Gaucho, Troiani Italian Grill, Rippies's Steakhouse Pier 70"
        details = "Delivered high standards of fine dining service. \n\n Weekly wine and service classes and recruitment of guests to join company club. \n\n Award Winner of **Washington Grand Wine Award** for 2005, 2006 and 2007. \n\n Responsible for private dining and beverage service for groups of 7-50 guests. \n\n Responsible for beverage inventory, scheduling, forecasitng and budgeting labor. \n\n Supervision of front of house staff members including hiring, training, coaching."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Management"
        level = "95%"
                
        [[params.skills.list]]
        skill = "Restaurant Accounting/Systems"
        level = "90%"

        [[params.skills.list]]
        skill = "Cost Control"
        level = "95%"

        [[params.skills.list]]
        skill = "Microsoft Professional"
        level = "95%"

        [[params.skills.list]]
        skill = "Product Knowledge"
        level = "99%"

        [[params.skills.list]]
        skill = "Coordinating/Planning"
        level = "90%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Isac Cantu 2018"
